### ISSUE TITLE
Missing rtl_tcp.h in the installation

### ISSUE THREAD

**Issue by f4exb** [librtlsdr/librtlsdr#21]
Compilation with librtlsdr breaks because rtl-sdr.h includes rtl_tcp.h but rtl_tcp.h is not part of the installation. It is missing in the list of installed includes in include/CMakeLists.txt

**Comment by racerxdl** [comment]
What OS are you using? Here it works fine on Linux.

**Comment by racerxdl** [comment]
Also, rtl-sdr.h shouldn't include rtl_tcp.h

**Comment by racerxdl** [comment]
Ok so the rtl-sdr shouldn't include rtl_tcp.h but the rtl_tcp.h should be included to CMakeList install. So I made a PR to fix it.

**Comment by f4exb** [comment]
Verified OK
