### ISSUE TITLE
On latest 64-bit windows build fails to start some of rtlsdr's executables.

### ISSUE THREAD

**Issue by wgaylord** [librtlsdr/librtlsdr#53]
The error is "The program can't start because libwinpthread-1.dll is missing from your computer. Try reinstalling the program to fix this problem"

Affected:
rtl_fm
rtl_tcp
rtl_adsb

All other work.

**Comment by wgaylord** [comment]
I am pretty sure this can be closed.

**Comment by 0x5c** [comment]
What was the solution?

**Comment by wgaylord** [comment]
A new build came out that was properly compiled. (With libs included instead of external)

**Comment by 0x5c** [comment]
when was that build?
I downloaded the latest available release and I have that error.

**Comment by wgaylord** [comment]
I don't remember currently.
