### ISSUE TITLE
Cannot find tuner

### ISSUE THREAD

**Issue by ghost** [librtlsdr/librtlsdr#60]
My issue is that rtl_entropy cannot find the tuner although it is detected by lsusb.

I've build rtl_entropy with the latest librtlsdr and contacted the author and they stated that the issue could be with librtlsdr. Any ideas?

Here is the dmesg output:

[  213.321989] usb 1-3: new high-speed USB device number 5 using ehci-pci
[  213.481903] usb 1-3: New USB device found, idVendor=0bda, idProduct=2838
[  213.481909] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  213.481913] usb 1-3: Product: RTL2838UHIDIR
[  213.481917] usb 1-3: Manufacturer: Realtek
[  213.481920] usb 1-3: SerialNumber: 00000001

foo@bar:~$ lsusb
Bus 001 Device 004: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T

foo@bar:~$ rtl_entropy
Options parsed, continuing.
Found 1 device(s):
  0:  Generic RTL2832U OEM
Using device 0: Generic RTL2832U OEM
No supported tuner found
Enabled direct sampling mode, input 1
Exact sample rate is: 2675000.143941 Hz
Setting Frequency to 101500000
Your device is capable of gains at...
 : 0.00
Setting gain to 0.00
Doing FIPS init
Reading samples in sync mode...

**Comment by itdaniher** [comment]
"tuner" in this case refers specifically to the frontend chip on your receiver, typically an R820T or a E4000 part, not to the USB stick as a whole.

If it's trivial to look at the circuit board inside your USB stick, you might have luck opening it and looking at the chip closest to your RF connection port. 

For what it's worth, for use as an entropy source, I don't think the tuner part itself is required - you should be able to get good noise by setting a high gain on the RTL2832U itself, but this would likely require source modifications to rtl_entropy.

**Comment by ghost** [comment]
It is an R820T. I'm starting to think its DOA.

Not sure if this helps? I'm not sure but it seems like rtlsdr_i2c_read_reg() isn't returning R82XX_CHECK_VAL like it _should_ ?

foo@bar$ udevadm info /dev/bus/usb/001/003
P: /devices/pci0000:00/0000:00:0c.0/usb1/1-2
N: bus/usb/001/003
E: BUSNUM=001
E: DEVNAME=/dev/bus/usb/001/003
E: DEVNUM=003
E: DEVPATH=/devices/pci0000:00/0000:00:0c.0/usb1/1-2
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_FOR_SEAT=usb-pci-0000_00_0c_0-usb-0_2
E: ID_MODEL=RTL2838UHIDIR
E: ID_MODEL_ENC=RTL2838UHIDIR
E: ID_MODEL_FROM_DATABASE=RTL2838 DVB-T
E: ID_MODEL_ID=2838
E: ID_PATH=pci-0000:00:0c.0-usb-0:2
E: ID_PATH_TAG=pci-0000_00_0c_0-usb-0_2
E: ID_REVISION=0100
E: ID_SERIAL=Realtek_RTL2838UHIDIR_00000001
E: ID_SERIAL_SHORT=00000001
E: ID_SOFTWARE_RADIO=1
E: ID_USB_INTERFACES=:ffffff:
E: ID_VENDOR=Realtek
E: ID_VENDOR_ENC=Realtek
E: ID_VENDOR_FROM_DATABASE=Realtek Semiconductor Corp.
E: ID_VENDOR_ID=0bda
E: MAJOR=189
E: MINOR=2
E: PRODUCT=bda/2838/100
E: SUBSYSTEM=usb
E: TAGS=:uaccess:seat:
E: TYPE=0/0/0
E: USEC_INITIALIZED=137179533
