### ISSUE TITLE
Compiling on macOS fails.

### ISSUE THREAD

**Issue by getoffmyhack** [librtlsdr/librtlsdr#69]
Attempting to compile on macOS fails, here are the specifics:

macOS 10.14.4
cmake 3.13.4 (as installed from MacPorts)
libusb-1.0 (as installed from MacPorts)
Xcode 10.2.1
I just cloned the development branch of librtlsdr/librtlsdr

I have tried to look for the obvious things in terms of paths, etc.  It finds my libusb-1.0 in /opt/local/lib, where MacPorts installs its packages, although the error message upon attempting to build using cmake: 
CMake Error at CMakeLists.txt:77 (message):
  LibUSB 1.0 required to compile rtl-sdr
Although reading through the CMakeError.log file seems to indicate that -lpthreads failed to link.

I am not familiar enough with the rlt-sdr build process to find out where I can attempt to fix it.   I will post below the output of the cmake command, the CMakeOutput.log and CMakeError.log below. 

FWIW, I am using the MacPorts version of librtlsdr for my [Swift macOS SDR app](https://github.com/getoffmyhack/waveSDR) but would like to update to the latest  here code as I start to dig in and learn more about the hardware itself as eventually I want to replace all the libusb calls to native IOKit calls, but I still have quite a ways to go before I get there.

Any guidance will be greatly appreciated!!

Thanks,

Justin

Here is the output of the cmake command:

[imac:SDR/librtlsdr/build] justin% cmake ../
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Looking for libusb_handle_events_timeout_completed
-- Looking for libusb_handle_events_timeout_completed - found
-- Looking for libusb_error_name
-- Looking for libusb_error_name - found
-- libusb-1.0 not found.
CMake Warning (dev) at /opt/local/share/cmake-3.13/Modules/CheckIncludeFiles.cmake:110 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /opt/local/lib/libusb-1.0.dylib

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  cmake/Modules/FindThreads.cmake:121 (CHECK_INCLUDE_FILES)
  CMakeLists.txt:74 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:77 (message):
  LibUSB 1.0 required to compile rtl-sdr

-- Configuring incomplete, errors occurred!
See also "/Users/justin/Sync/Development/SDR/librtlsdr/build/CMakeFiles/CMakeOutput.log".
See also "/Users/justin/Sync/Development/SDR/librtlsdr/build/CMakeFiles/CMakeError.log".

And below are the log files:

[CMakeOutput.log](https://github.com/librtlsdr/librtlsdr/files/3194566/CMakeOutput.log)
[CMakeError.log](https://github.com/librtlsdr/librtlsdr/files/3194567/CMakeError.log)

**Comment by hayguen** [comment]
closing this .. see https://github.com/librtlsdr/librtlsdr/issues/89
