### ISSUE TITLE
Use librtlsdr with Python

### ISSUE THREAD

**Issue by YorkLeSec** [librtlsdr/librtlsdr#73]
Hello all,

I use librtlsdr to do a plane radar. First i used pyrtlsdr to remote my device but it didn't seem to work. Then i used dump1090 to check and it worked fine. But i can not use it for different reasons on my project.
I decided then to create my own "module" working with librtlsdr.
I read pyrtlsdr to found out how it works. I am stuck at openning with rtlsdr_open function. One argument is a double pointer to a struct. Pyrtlsdr says that we don't need it and create a fake pointer to use it. But i think that this is not true and it is not working when i try to set frequency for example after that (-1 return).
Do i have to create i class, then use it for calling my function ?

I am a beginner in programming so i might not have all notions.

Thank you all

**Comment by hayguen** [comment]
i don't see a reason why pyrtlsdr should not work.
The common C interface is the the same as librtlsdr from osmocom, we just added a few functions.
Without more infos (example source), it's difficult to help you.

anyways:
https://github.com/librtlsdr/librtlsdr/blob/master/include/rtl-sdr.h
declares RTLSDR_API int rtlsdr_open(rtlsdr_dev_t **dev, uint32_t index);
meaning you give a pointer to a pointer and an index .. to get the pointer filled with the device "handle".
of course, you should check the return code.
