### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by hayguen** [librtlsdr/librtlsdr#78]
can someone setup github actions
with compilation of master and development branches
on several platforms (Linux, Windows and MacOS) with several compilers?

**Comment by ValZapod** [comment]
It may be also nice to set up https://app.circleci.com/pipelines/github/librtlsdr/librtlsdr/jobs/100
See docs how to update to v2.0 docs https://circleci.com/sunset1-0/

**Comment by hayguen** [comment]
added github actions .. to build linux and macos.
windows looks some complicated ..

now realize the comment on circleci
@jpoirier : can you have a look at this?
think, the more platforms/compiler, the better.

**Comment by hayguen** [comment]
also added windows 32/64 build with github actions
