### ISSUE TITLE
RTLSDR dongle with BiasT NOT on GPIO Pin 0 ?

### ISSUE THREAD

**Issue by hayguen** [librtlsdr/librtlsdr#80]
https://www.rtl-sdr.com/ provides V3 dongles with BiasT circuit connected at GPIO Pin 0.
NooElec has RTLSDR-models having BiasT ALWAYS on.
Which manufacturer provides RTLSDR dongles with BiasT NOT on Pin 0 ?

**Comment by rtlsdrblog** [comment]
As far as i'm aware we're the only manufacturer using a software controlled bias tee. 

Some people use the GPIO expansion ports on the Blog V3 dongles for various purposes though, so being able to control the GPIO individually is an advantage.

**Comment by hayguen** [comment]
thank you for this info.
